name: lint markdown files

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    env:
      FAIL: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install moonbit runtime
        run: |
          /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/install/unix.sh)"
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
          npm install -g @moonbit/markdown-linter
      - name: lint markdowns
        run: |
          find . -name '*.md' | while read file; do
            echo "========mdlint results for $file========";
            mdlint "$file" || FAIL=$?;
            if [[ $FAIL -eq 1 ]]; then
              echo "========mdlint failed for $file========"
            fi
          done
          if [[ $FAIL -eq 1 ]]; then exit 1; fi
